# Generated by Django 4.0.6 on 2022-07-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_locations_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
