# Generated by Django 4.0.6 on 2022-07-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ads_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='Member', max_length=30),
        ),
    ]
