# Generated by Django 4.0.6 on 2022-07-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
    ]
