# Generated by Django 4.0.6 on 2022-07-14 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_rename_locations_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.user'),
        ),
    ]
