# Generated by Django 4.0.6 on 2022-07-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_ads_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ads',
            name='price',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
